name: flutter_app_update_notifier
description: "A Flutter package that alerts users when app updates are available, supporting both optional and mandatory update prompts."
version: 1.0.0
repository: https://github.com/geraldcrispy/app-update-notifier
homepage: hhttps://github.com/geraldcrispy/app-update-notifier
topics: [flutter, app-updates, mandatory, optional]

platforms:
  android:
  ios:
  macos:
  windows:

environment:
  sdk: ^3.0.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ^8.3.0
  pub_semver: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0
